#!/bin/bash
#SBATCH -p rome16q # partition (queue)
#SBATCH -N 4 # number of nodes
#SBATCH --ntasks-per-node 1  # number of cores
#SBATCH -t 0-00:10 # time (D-HH:MM)
#SBATCH -o 4omp.%j.out # STDOUT
#SBATCH -e slurm.%j.err # STDERR
#SBATCH --exclusive
module load openmpi-4.0.5
srun build/debug/CSR