#!/bin/bash
#SBATCH -p rome16q # partition (queue)
#SBATCH -N 4 # number of nodes
#SBATCH --ntasks-per-node 1  # number of cores
#SBATCH --cpus-per-task 16 # number of cores per task

#SBATCH -t 0-00:10 # time (D-HH:MM)
#SBATCH -o 4omp.%j.out # STDOUT
#SBATCH -e slurm.%j.err # STDERR
#SBATCH --exclusive

omp_threads=$SLURM_CPUS_PER_TASK
export OMP_NUM_THREADS=$omp_threads
module load openmpi-4.0.5
srun build/debug/CSR